### PR TITLE
Added support for recordmeet security cookie.

### PR DESCRIPTION
**Pull request by albyrock87**
Hi,

this should add a manual support for [authenticated recorded meetings](https://github.com/Battleman/zoomdl/issues/20#issuecomment-700854788).

I found out that the only required cookie is `_zm_web_recordmeet`.

I added also the support for SSO with `_zm_kms` cookie.

Thanks for this awesome tool!

### CODE REVIEW

**Review by Battleman — CHANGES_REQUESTED** [review]
Thanks a lot for your PR, and sorry for now reacting sooner, I kinda forgot about it.
The whole `_set_recordmeet` feels artificial, would be clearer to move its content to `__init__`

**Comment by Gh0stByte** [comment]
I'm not quite sure where you're grabbing ```_zm_web_recordmeet``` from..

**Comment by albyrock87** [comment]
Cleaned up the `_set_recordmeet` (I was inspired from the `_set_cookies` method, but I agree with you).
About the `_zm_web_recordmeet`, I'm requesting it to the user and he can find it in browser's developer tools after logging in to the video page.

I know this is not the preferred way to do that, but until @Battleman finds a way to include `browser_cookie3` or something else, this is a way to download the video.

**Review by Battleman — APPROVED** [review]
lgtm

**Comment by Battleman** [comment]
All good for me. I'll merge it within the next 1-2 days. I'm kind of on holidays rn, I don't have all the tools to test and compile. At latest this weekend. Thanks again for the contribution!

**Comment by yannip1234** [comment]
My SSO Auth Zoom link does not have a _zm_web_recordmeet cookie.

**Comment by Gh0stByte** [comment]
@yannip1234 same. for SSO you need the ```_zm_kms``` cookie as I outlined in #20

**Comment by albyrock87** [comment]
Hi, I added the support for `_zm_kms` :)

**Comment by Gh0stByte** [comment]
@albyrock87 wanna add support for ```_km_page_auth``` as well? It seems that different SSO services result in different cookies. Also adding a -c arg where you can specify a unique cookie(s) may prove helpful as well.

**Comment by Battleman** [comment]
OK, thanks. I'm merging into Beta (as explained in [another PR](https://github.com/Battleman/zoomdl/pull/40#issuecomment-779444146)). These two use the same method to achieve a slightly different problem, adding 2 commands at once. Kinda hardcoded, but OK for now.

**Pull request merged**
