### PR TITLE
Implement system exit code on error

### LINKED ISSUE #76: Implement exit statuses
**Prerequisite**

- [x] I have updated to the latest version,
- [] (If applicable) I have ensured the password is correct with the flag `-v 0`,
- [x] I have searched the opened and closed issues for a duplicate,

**Describe the bug**

I wanted to use zoomdl as part of a bash script I am writing for myself to download videos to a ramdisk and upload it directly to my cloud storage. However, I discovered that even if something fails, zoomdl will only print out error messages to the console but not set an exit status so my script can react properly. Zoomdl will report successful completion to the shell in any case.

**To Reproduce**

1. Use a bad/expired zoom recording link
2. Zoomdl will report something like "[ERROR] Video not found in page. Is it login-protected?" in the shell
3. The shell will report that zoomdl terminated successfully with exit code 0 and await your input again
4. So if you want to do some error handling as part of a larger script, you're out of luck

**Expected behavior**

Zoomdl is distributed as an executable (not just a raw python script) and thus meant to be run in a shell, so it should also report standard shell exit codes.

**Screenshots**

**URL (opt)**

<any expired/invalid zoom recording link>
for example: https://www.zoom.us/rec/play/404

**Logs**

```
~ >  ./zoomdl -u https://www.zoom.us/rec/play/404 -v 0
Using standard Windows UA
Changing page to https://www.zoom.us/rec/play/404
Advanced meta failed
Unable to extract chatList from page
Unable to extract transcriptList from page
Metas are {'cookie_currency': 'EUR', 'currency_symbol': '€', '__platformCheck': '', 'detect': 'https://st2.zoom.us/cdn-detect.png', 'chatList': [], 'transcriptList': []}
No video URL in meta, going bruteforce
[ERROR] Video not found in page. Is it login-protected? 
Try to refresh the webpage, and export cookies again
Unable to find metadata, aborting.

~ > echo $?
0
```
**Versions (please complete the following information):**
 - OS: macOS Big Sur 11.6
 - Python Version: homebrew python@3.9 (3.9.13)

**Additional context (opt)**
I want this line to work as intended in my shell script:
` ${script_dir}/zoomdl -u "$url" -f "$filename" || continue`
If zoomdl encounters an error, it should return a non-zero exit code to the shell such that the `continue` statement is executed and skips the rest of the loop this line is contained in.

### PR DESCRIPTION
**Pull request by niklasbogensperger**
Would solve my own open issue.
Closes #76 
There is potential to implement more granular exit codes in the future.

### CODE REVIEW

**Comment by niklasbogensperger** [comment]
Sample log output (see my issue for comparison):

```
❯ ./zoomdl -u https://www.zoom.us/rec/play/404 -v 0
Using standard Windows UA
Changing page to https://www.zoom.us/rec/play/404
Advanced meta failed
Unable to extract chatList from page
Unable to extract transcriptList from page
Metas are {'cookie_currency': 'EUR', 'currency_symbol': '€', '__platformCheck': '', 'detect': 'https://st2.zoom.us/cdn-detect.png', 'chatList': [], 'transcriptList': []}
No video URL in meta, going bruteforce
[ERROR] Video not found in page. Is it login-protected? 
Try to refresh the webpage, and export cookies again
Unable to find metadata, aborting.

❯ echo $?
1
```

**Comment by niklasbogensperger** [comment]
I just realized that there are indeed some sys.exit() statements already implemented (also in another pull request, #75; ex. [line](https://github.com/Battleman/zoomdl/blob/83f54e220d9edeef728ddb954877f7bb1ccdc917/zoom_dl/zoomdl.py#L418)), but not all errors are actually covered as evidenced by the log in my issue.

I don't know which solution you prefer (a sys.exit() after every individual error vs. a sys.exit(exit_code) at the end of the script) but I think it would be good if it is implemented consistently.

**Comment by Battleman** [comment]
I see the problem. I'll merge that one into Beta and see what looks best. Thanks for the contribution.

**Comment by niklasbogensperger** [comment]
> I see the problem. I'll merge that one into Beta and see what looks best. Thanks for the contribution.

Thanks! Let me know if I can help at all with implementing.

**Pull request merged**
