### PR TITLE
Adds support for SSO authentication

### LINKED ISSUE #20: Unable to download from auth-protected URLs
Encountering this issue while attempting to download a lecture. These lectures are behind a custom zoom setup for my school (could be part of the issue) where the URL begins with https://*schoolname*.zoom.etc

The following error occurs while attempting a download with a password
```
C:\Users\Gh0st\Downloads\Portable>zoomdl.exe -u "https://*redacted*" -p "gH92b$ZG"
Traceback (most recent call last):
  File "zoom_dl\__main__.py", line 20, in <module>
  File "zoom_dl\__init__.py", line 18, in main
  File "zoom_dl\zoomdl.py", line 135, in download
UnboundLocalError: local variable 'meet_id' referenced before assignment
[6720] Failed to execute script __main__
```

Current Environment is
>Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32

Also tried on WSL with no success
> Linux Gh0st-PC 4.19.84-microsoft-standard #1 SMP Wed Nov 13 11:44:37 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "./zoomdl/__main__.py", line 20, in <module>
  File "./zoomdl/zoom_dl/__init__.py", line 18, in main
  File "./zoomdl/zoom_dl/zoomdl.py", line 135, in download
UnboundLocalError: local variable 'meet_id' referenced before assignment
```

This error occurs when attempting a download which does not require a password but does require you to be logged in (in both environments.)

```No video URL in meta, going bruteforce
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "./zoomdl/__main__.py", line 20, in <module>
  File "./zoomdl/zoom_dl/__init__.py", line 18, in main
  File "./zoomdl/zoom_dl/zoomdl.py", line 142, in download
  File "./zoomdl/zoom_dl/zoomdl.py", line 80, in get_page_meta
AttributeError: 'NoneType' object has no attribute 'group'
```

Perhaps incorporate an argument to supply a cookie/auth string to enable downloads

### PR DESCRIPTION
**Pull request by Gh0stByte**
Fixes #20 - Allows usage of _zm_page_auth  and _zm_kms cookies to bypass sso authentication. 
Edit: Fixed typo. Thank @yannip1234

### CODE REVIEW

**Comment by yannip1234** [comment]
Ah, I see. My Zoom link does not have that cookie either. It seems like I have _zm_page_auth.

**Comment by Gh0stByte** [comment]
@yannip1234 My bad. Typo in the pull req. Thanks for the heads up

**Comment by yannip1234** [comment]
@Gh0stByte No problem. I tried downloading your branch and compiling it using the devscripts.sh. I tried it like this: zoomdl -u '[link here]' -a '[cookie here]' and I am getting an unrecognized arguments error. Am I not compiling this thing right?

**Comment by Gh0stByte** [comment]
Strange. Must be something the utils.py. I’ll check it out when I get home.  Sent from Mail for Windows 10 From: yannip1234Sent: Friday, February 12, 2021 2:51 PMTo: Battleman/zoomdlCc: Matthew Matter; MentionSubject: Re: [Battleman/zoomdl] Adds support for SSO authentication (#40) @Gh0stByte No problem. I tried downloading your branch and compiling it using the devscripts.sh. I tried it like this: zoomdl -u '[link here]' -a '[cookie here]' and I am getting an unrecognized arguments error. Am I not compiling this thing right?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by yannip1234** [comment]
@Gh0stByte Any update?

**Comment by Gh0stByte** [comment]
> 
> 
> @Gh0stByte Any update?

Yeah, so when you compiled it, you must not have compiled my branch. I updated the cookie, since it's actually ```_zm_ssid``` rather than ```_zm_page_auth``` and was able to download without any issue. 
Screenshot_5

I've attached the windows exe for you to try. Let me know if it works for you too.


[zoomdl.zip](https://github.com/Battleman/zoomdl/files/5982366/zoomdl.zip)

**Comment by Gh0stByte** [comment]
And just a note, I believe the ```_zm_kms``` is for password protected corporate links and ```_zm_ssid``` is strictly for SSO. Before I transferred this semester, the domain used the zoom login and the cookie was ```_zm_kms```. This semester, however, it's SSO and the cookie is ```_zm_ssid```. I can still, however, access lectures from last semester with the url and ```_zm_kms```

**Comment by Battleman** [comment]
All good, thanks for the PR. Merging into beta. With 2 PR on cookies, I might merge them into a single command, so I don't want to create a history and changing the commands later.

**Comment by Gh0stByte** [comment]
> 
> 
> All good, thanks for the PR. Merging into beta. With 2 PR on cookies, I might merge them into a single command, so I don't want to create a history and changing the commands later.

Glad to help. Yeah totally, I think maybe a generic -c --cookie command may be a better option long-term.

**Comment by yannip1234** [comment]
@Gh0stByte thanks for the update. I have downloaded the latest beta branch of Zoomdl. My zoom links do contain _zm_ssid, but I am getting "Advanced meta failed". Trying with _zm_page_auth fails too. Any pointers?

**Pull request merged**
